# scenarios.py - 11주차 거시경제 시나리오 및 브리핑 데이터

SCENARIOS = {
    1: {
        "round_name": "Round 1 (2주차)",
        "phase": "영업 개시 및 시장 탐색기",
        "base_rate": 2.50,
        "gdp_growth": 2.5,
        "market_deposit_base": 10000.0,
        "market_loan_base": 8000.0,
        "gov_bond_yield": 2.70,
        "corp_bond_yield": 3.80,
        "base_npl_rate": 1.0,
        "news_headline": "📢 [금융 브리핑] 안정적인 경기 흐름 속 은행 영업 개시",
        "news_detail": "한국은행은 기준금리를 2.50%로 유지했습니다. 완만한 경기 성장세 속에서 각 은행은 초기 예대금리 전략을 수립해 고객 기반을 확보해야 합니다.",
        "instructor_tip": "예대마진(NIM)과 시장점유율의 상관관계를 확인하고, 극단적인 금리 경쟁의 위험성을 안내하세요."
    },
    2: {
        "round_name": "Round 2 (3주차)",
        "phase": "경기 호황 및 대출 수요 급증",
        "base_rate": 2.75,
        "gdp_growth": 3.8,
        "market_deposit_base": 11000.0,
        "market_loan_base": 9800.0,
        "gov_bond_yield": 2.95,
        "corp_bond_yield": 4.10,
        "base_npl_rate": 0.8,
        "news_headline": "📈 [산업 동향] 기업 설비투자 확대, 대출 수요 폭증!",
        "news_detail": "경기가 가파르게 성장하며 기업과 가계의 대출 수요가 급증했습니다. 대출 자산을 늘릴 호기이나, 외형 확장에 따른 자기자본비율(BIS) 하락에 유의해야 합니다.",
        "instructor_tip": "공격적 대출 확장이 이익을 늘리지만 위험가중자산(RWA) 증가로 BIS비율을 떨어뜨릴 수 있음을 강조하세요."
    },
    3: {
        "round_name": "Round 3 (4주차)",
        "phase": "인플레이션 압박 및 금리 인상기",
        "base_rate": 3.75,
        "gdp_growth": 2.0,
        "market_deposit_base": 11200.0,
        "market_loan_base": 9200.0,
        "gov_bond_yield": 3.90,
        "corp_bond_yield": 5.20,
        "base_npl_rate": 1.2,
        "news_headline": "🔥 [통화 정책] 인플레이션 비상! 기준금리 1.00%p 전격 인상",
        "news_detail": "중앙은행이 빅스텝 금리 인상을 단행했습니다. 시중 예금 조달비용이 빠르게 증가하므로 ALM(금리 갭 리스크) 관리가 필수적입니다.",
        "instructor_tip": "단기 조달(예금) - 장기 운용(대출) 구조에서 금리 상승기가 조달비용에 미치는 충격을 설명하세요."
    },
    4: {
        "round_name": "Round 4 (5주차)",
        "phase": "고금리 지속 및 은행 간 예금 전쟁",
        "base_rate": 4.50,
        "gdp_growth": 1.2,
        "market_deposit_base": 11500.0,
        "market_loan_base": 8800.0,
        "gov_bond_yield": 4.60,
        "corp_bond_yield": 6.10,
        "base_npl_rate": 1.8,
        "news_headline": "⚔️ [금융권 경쟁] 유동성 흡수 심화, 시중은행 '고금리 특판' 출혈경쟁",
        "news_detail": "시중 유동성이 마르면서 은행 간 예금 유치 전쟁이 격화되고 있습니다. 금리를 낮추면 예금이 급격히 이탈하고, 높이면 마진이 급감합니다.",
        "instructor_tip": "마케팅비와 예금금리 조합을 통해 조달 유동성을 방어하는 전략적 의사결정을 유도하세요."
    },
    5: {
        "round_name": "Round 5 (6주차)",
        "phase": "경기 둔화 및 잠재 부실 누적",
        "base_rate": 4.50,
        "gdp_growth": 0.5,
        "market_deposit_base": 11300.0,
        "market_loan_base": 8200.0,
        "gov_bond_yield": 4.40,
        "corp_bond_yield": 6.50,
        "base_npl_rate": 2.5,
        "news_headline": "⚠️ [위험 징후] 고금리 장기화로 자영업자·중소기업 이자 부담 한계",
        "news_detail": "경기가 급격히 둔화되며 연체율이 상승하기 시작했습니다. 과거 무분별하게 대출 심사를 완화했던 은행들의 건전성에 빨간불이 켜졌습니다.",
        "instructor_tip": "대출 심사 기준(공격적 vs 보수적)의 누적 효과가 본격적으로 차이를 만들기 시작함을 보여주세요."
    },
    6: {
        "round_name": "Round 6 (7주차)",
        "phase": "[충격] 신용경색 및 부실 쇼크",
        "base_rate": 4.25,
        "gdp_growth": -0.8,
        "market_deposit_base": 10500.0,
        "market_loan_base": 7500.0,
        "gov_bond_yield": 4.00,
        "corp_bond_yield": 7.80,
        "base_npl_rate": 4.2,
        "news_headline": "💥 [금융 위기] 중견기업 연쇄 도산 및 부동산 PF 부실 쇼크!",
        "news_detail": "마이너스 성장에 진입하며 신용위기가 터졌습니다. 은행권 전반에 부실채권(NPL)이 폭증하고, 거액의 대손충당금 전입으로 순이익이 급감합니다.",
        "instructor_tip": "BIS 비율 10.5% 방어가 최대 과제입니다. 충당금 전입과 자본 훼손을 어떻게 극복하는지 관찰하세요."
    },
    7: {
        "round_name": "Round 7 (8주차)",
        "phase": "감독당국의 규제 강화",
        "base_rate": 3.75,
        "gdp_growth": 0.2,
        "market_deposit_base": 10800.0,
        "market_loan_base": 7800.0,
        "gov_bond_yield": 3.60,
        "corp_bond_yield": 6.50,
        "base_npl_rate": 3.2,
        "news_headline": "📜 [규제 감독] 금융감독원, '은행 자본적정성 관리 강화 및 배당 자제 권고'",
        "news_detail": "감독당국이 부실 은행에 대한 경영개선 권고를 시작했습니다. 배당을 억제하고 이익을 사내 유보하여 자기자본비율을 정상화해야 합니다.",
        "instructor_tip": "위기 극복을 위한 디레버리징(자산 축소) 및 내부유보 중심의 자본 확충 전략을 피드백하세요."
    },
    8: {
        "round_name": "Round 8 (9주차)",
        "phase": "금리 인하 사이클 및 경기 회복기",
        "base_rate": 2.75,
        "gdp_growth": 1.8,
        "market_deposit_base": 11400.0,
        "market_loan_base": 8600.0,
        "gov_bond_yield": 2.90,
        "corp_bond_yield": 4.50,
        "base_npl_rate": 1.9,
        "news_headline": "🌱 [경기 회복] 한국은행 금리 전격 인하, 시장 정상화 시동",
        "news_detail": "기준금리가 인하되며 채권 가격이 상승(평가이익)하고 대출 수요가 회복됩니다. 건전성을 지켜낸 은행들이 재도약할 기회입니다.",
        "instructor_tip": "금리 하락기에 유가증권(국채/회사채) 포트폴리오가 창출하는 평가이익과 회복세를 확인하세요."
    },
    9: {
        "round_name": "Round 9 (10주차)",
        "phase": "최종 결산 라운드",
        "base_rate": 2.50,
        "gdp_growth": 2.2,
        "market_deposit_base": 12000.0,
        "market_loan_base": 9500.0,
        "gov_bond_yield": 2.65,
        "corp_bond_yield": 3.90,
        "base_npl_rate": 1.2,
        "news_headline": "🏁 [마지막 분기] 9개 분기 경영 대장정 마무리, 최종 주주가치 결정",
        "news_detail": "모든 시련을 거쳐 최종 결산에 도달했습니다. 최종 배당 정책과 포트폴리오 정리를 통해 최종 기업가치와 누적 ROE를 극대화하세요.",
        "instructor_tip": "최종 순위는 누적 ROE, 최종 주가, BIS 건전성을 종합 평가함을 상기시키세요."
    }
}